name: gmusic_proxy_helper
version: 0.0.1
description: A simple console application.
author: Joel Trottier-Hebert <iamquebecois@gmail.com>
dependencies:
  http: '>=0.11.3+3 <0.12.0'
  unscripted: '>=0.6.2 <0.7.0'
dev_dependencies:
  test: '>=0.12.12 <0.13.0'
